[General]
__userfile__=true
iconTheme=

[customcommand]
alignment=Right
click=rofi -show drun
command=
icon=applications-all
outputFormat=0
repeat=false
runWithBash=false
text=
tooltip=Launcher (Super+A)
type=customcommand

[customcommand2]
alignment=Right
click=rofi -show window
command=
icon=window_list
outputFormat=0
repeat=false
repeatTimer=5
runWithBash=false
text=
tooltip=Window Switcher (Super+W)
type=customcommand

[customcommand3]
alignment=Right
click=rofi -show power-menu -modi power-menu:'~/.config/rofi/rofi-power-menu' -no-show-icons
command=
icon=system-shutdown
repeat=false
runWithBash=true
text=
tooltip=Power Options (Super+Q)
type=customcommand

[customcommand4]
alignment=Right
click=rofi -show filebrowser
command=
icon=folder
outputFormat=0
repeat=false
runWithBash=false
text=
tooltip=Rofi Filebrowser (Super+E)
type=customcommand

[customcommand5]
alignment=Right
click=sh -c \"python3 $HOME/.config/lxqt/stats.py --cpu\"
command=python3 ./.config/lxqt/stats.py --cpu
icon=cpu
maxWidth=200
outputFormat=0
repeatTimer=1
runWithBash=false
text=%1
tooltip=CPU Usage: %1
type=customcommand
wheelUp=

[customcommand6]
alignment=Right
click=sh -c 'notify-send \"All RAM Stats\" \"$(python3 $HOME/.config/lxqt/stats.py --ram --all)\"'
command=python3 ./.config/lxqt/stats.py --ram
icon=device_mem
maxWidth=200
outputFormat=0
repeatTimer=5
runWithBash=false
text=%1
tooltip=RAM Usage
type=customcommand
wheelUp=

[customcommand7]
alignment=Right
click=
command=python3 ./.config/lxqt/stats.py --disk
icon=drive-harddisk
text=%1
tooltip=Disk Usage for /
type=customcommand

[customcommand8]
alignment=Right
click=
command=sh -c \"lxqt-backlight_backend --show | awk '{print ($3/$2*100)}' | awk -F \".\" '{print $1}'\"
icon=brightness
maxWidth=200
repeatTimer=1
runWithBash=false
text=%1 %
tooltip=Scroll to adjust brightness (python script todo)
type=customcommand
wheelDown=lxqt-backlight_backend --dec
wheelUp=lxqt-backlight_backend --inc

[desktopswitch]
alignment=Left
labelType=0
showOnlyActive=false

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=24
lineCount=1
lockPanel=false
opacity=100
panelSize=35
plugins=customcommand, customcommand2, customcommand4, spacer2, desktopswitch, spacer, customcommand5, customcommand6, customcommand7, customcommand8, volume, worldclock, showdesktop, customcommand3
position=Top
reserve-space=true
screen-name=eDP-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[spacer]
alignment=Left
expandable=true
spaceType=invisible
type=spacer

[spacer2]
alignment=Left
size=10
spaceType=invisible
type=spacer

[volume]
alignment=Right
alwaysShowNotifications=false
showKeyboardNotifications=true

[worldclock]
alignment=Right
autoRotate=true
customFormat=HH:mm:ss
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=false
showTimezone=false
showTooltip=true
showWeekNumber=true
timeAMPM=false
timePadHour=false
timeShowSeconds=true
timeZoneWheel=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=true
