# tmux.conf
# This will be extremely similar to my existing fvwm. 

## BASE

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
 
# Enable mouse support
set -g mouse on

# Change prefix to Ctrl+a (more ergonomic)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set pane separator to be thicker
set -g pane-border-lines double

## BINDINGS

# Reload config
bind R source-file ~/.tmux.conf \; display "Config reloaded!"

# run a shell command
bind a command-prompt -I "" { run-shell "%%" }

# Rename Window
bind n command-prompt -I "#W" { rename-window -- "%%" }

# switch window
bind -r Tab select-window -n
bind -r BTab select-window -p

# Better pane splitting (and keep current path)
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind Enter new-window -c "#{pane_current_path}"

# Switch panes via arrow keys
bind -r Left  select-pane -L
bind -r Right select-pane -R
bind -r Up    select-pane -U
bind -r Down  select-pane -D

bind -n S-Left resize-pane -L 5
bind -n S-Down resize-pane -D 2
bind -n S-Up resize-pane -U 2
bind -n S-Right resize-pane -R 5

# Enter resize mode
bind r switch-client -T resize

# Resize mode
bind -r -T resize Left  resize-pane -L 5
bind -r -T resize Right resize-pane -R 5
bind -r -T resize Up    resize-pane -U 2
bind -r -T resize Down  resize-pane -D 2

# Exit resize mode
bind -T resize Escape switch-client -T prefix
bind -T resize Enter  switch-client -T prefix
bind -T resize q      switch-client -T prefix

# swap panes
bind -r x swap-pane -D
bind -r X swap-pane -U

# Delete pane
bind C kill-pane

# Delete window
bind -n M-c kill-window

# Delete session
bind -n M-C kill-session

# Entire List
bind w choose-tree

# copy mode
bind s copy-mode
bind p paste-buffer
bind P list-buffers

## STATUS BAR AND COLOURS

# Format variables
#{session_name}       # Current session
#{window_index}       # Window number
#{window_name}        # Window name
#{pane_current_path}  # Current directory
#{host}               # Hostname

# Colors
set -g @bg "#222B40" 
set -g @fg "#BDE6FB" 
set -g @blue "#0078D7"

# Status bar
set -g status-bg "#222B40" 
set -g status-fg "#BDE6FB" 
set -g message-style "fg=#222B40,bg=#BDE6FB,fill=#BDE6FB"

# Pane borders
set -g pane-active-border-style "fg=#0078D7"
#set -g pane-border-style "fg=#3E424B"
set -g pane-border-style "fg=gray"

set -g popup-border-lines rounded
set -g menu-border-lines rounded

# Menu
set -g menu-style "bg=#222B30,fg=#BDE6FB"
set -g menu-selected-style "bg=#BDE6FB,fg=#222B30"
set -g menu-border-style "fg=#0078D7"

# Copy Mode, tree mode
set -g mode-style "bg=#BDE6FB,fg=black"

# Clock mode
set-option -g clock-mode-colour "#BDE6FB"

# Pane display
set-option -g display-panes-active-colour "#BDE6FB"
set-option -g display-panes-colour gray

## STATUS BAR

# Active Window
set -g window-status-current-style "bg=#BDE6FB,fg=#222B30,bold"

# Window Bell
set -g window-status-bell-style "fg=white,bg=red,bold"

# Status Bar Limits
set -g status-left-length 50
set -g status-right-length 100

# Status Bar Left
set-option -g status-left "#[bg=#0078D7,fg=#222B30][#S]#[default] "
# Status Bar Right
set-option -g status-right "[#{client_key_table}] | #[fg=colour03]#{user}@#H#[default] | #[fg=colour05]PID: #{pid}#[default] | #[fg=#107C10]tmux #{version}#[default] | #[fg=#75B5AA]%H:%M#[default] "
