#!/bin/sh

if ps aux | grep -E ' (openbox|Xorg|^X$)'; then
    # Commands for Openbox/xorg
    polybar &
    feh --bg-fill ~/.local/share/wallpapers/firewatchgreen.png &
else
    # Commands for LabWC/wayland
    kanshi &
    waybar & 
    swaybg -i ~/.local/share/wallpapers/firewatchgreen.png -m fill &
fi

dunst &

