#!/bin/sh

# Check if the WM is OpenBox
if ps aux | grep -E ' (openbox|Xorg|^X$)'; then
    # Commands for Openbox/xorg
    polybar &
    feh --bg-fill ~/.local/share/wallpapers/firewatchblue.png &
else
    # Commands for LabWC/wayland
    kanshi &
    waybar &
    swaybg -i ~/.local/share/wallpapers/firewatchblue.png -m fill &
    Xwayland :1 -rootless &
    export DISPLAY=:1
fi

# Check for the device-specific startup programs file
if [ -f ~/.config/wmadditionalstartupprograms-devicespecific ]; then
    sh -c ~/.config/wmadditionalstartupprograms-devicespecific &
fi

dunst &
