[window]
dimensions = { columns = 80, lines = 25 }
dynamic_title = true
title =	"Terminal Emulator"

[font]
normal = { family = "MesloLGS NF" }

[colors.primary]
background = "#0F111A"
foreground = "#FFFFFF"

[env]
TERM = "xterm-256color"
